### ISSUE TITLE
Numerical discrepancies

### ISSUE THREAD

**Issue by DavidMStraub** [DsixTools/python-smeftrunner#1]
Comment by @celis:

> using the same input cards for the SM and the WCs (the default ones downloaded from https://dsixtools.github.io) in Dsixtools and in the python-smeftrunner, we find in general numerical discrepancies on the output card for the WCs at the low scale.    Of course it would be important to understand the origin of these. 
> 
> for the SM parameters (gauge couplings, scalar potential and Yukawas) we find reasonably good numerical agreement between the two codes while performing the test mentioned above.  To get the good agreement we have set in the DsixTools option card: 
> 
> 5 0 # Use SM RGEs to compute SM parameters at the high-energy scale
> 
> meaning that the SM parameters given as inputs are taken to be at the high scale, so from this we guess this is how python-smeftrunner is working.

**Comment by DavidMStraub** [comment]
These numerical differences are important to sort out.

The logical possibilities of their origin are

1. Bug in reading the inputs
2. Bug in the beta functions
3. Differences in the numerical ODE solvers
4. Bug in writing the outputs

I can essentially rule out 2. because of [this unit test](https://github.com/DsixTools/python-smeftrunner/blob/master/smeftrunner/tests/test.py#L40-L58). I generated random values for *all* WCs and SM parameters in Mathematica, evaluated the beta functions with the Mathematica SMEFTrunner, and saved them as JSON files. Here, these files are read in in Python and compared to the python-smeftrunner beta functions. The agreement is a powerful check.

I also doubt that 1. or 4. are responsible.

So probably it is due to the ODE solvers. What would be good is to have another unit test that takes an input file and an output file generated by the Mathematica SMEFTrunner; could you provide such a pair of files, please? I would need one where the input parameters (SM & WCs) are all at the same scale.

**Comment by avelino3000** [comment]
Hi,

you can find [here](https://github.com/DsixTools/python-smeftrunner/files/1200599/test_DsixTools.tar.gz) a complete set of input values used in DsixTools and the resulting output file. As you can see, all the input values (SM parameters and WCs) were given at the same high-energy scale (10 TeV) and they were evolved down to 160 GeV.

By comparing to the same results obtained with your python module, it looks to me as a normalization issue, since they seem to differ by a global factor of 2 (at least in the cases that I checked). For instance, the WC2 and WC3 blocks are

With the **Mathematica package DsixTools**:

Block WC2
1 0.005772	# phi
Block WC3
1 0.006787	# phiBox
2 -0.001477	# phiD

With your **python-smeftrunner module**:

BLOCK WC2
    1    0.00288866916465
BLOCK WC3
    1    0.00339625574146
    2    -0.000738974304873

**Comment by celis** [comment]
Hi, 
we think it is not due to the 3. Differences in the numerical ODE solvers,
as we compare the outputs in the leading log approximation (no ODE routines involved) and we still find numerical discrepancies.

**Comment by DavidMStraub** [comment]
OK. If it's a factor of 2 it should be easy to find. @pxylisa is going to write a unit test to make sure the output file values agree between Mathematica & Python, now and in case of future changes.

**Comment by Demerzelx** [comment]
Hi,

You can find [here](https://github.com/pxylisa/python-smeftrunner/blob/master/smeftrunner/tests/differences/defaultblocks_py_ma_quotient.dat) values' differences of the common outputs' blocks. The first column is python output values, the second from mathematica, the third is the quotient between them. 

If the two values are both smaller than 5e-8 (I'm not sure how small this scale should be but it is variable in the code), or their quotient is between 0.95-1.05, the blocks' values will not be shown.  

[This](https://github.com/pxylisa/python-smeftrunner/blob/master/smeftrunner/tests/differences/blocks_diffences_ma.dat) shows all the blocks that were presented in mathematica's output file but not in python. It may be not so important because most of them are zeros.  

The code of the outputs' test and the forming of these two files are [here](https://github.com/DsixTools/python-smeftrunner/blob/master/smeftrunner/tests/test_smeft.py). 

We also tested the python outputs in the leading log approximation. The values accord well with the accurate output values of pythons'. The deviation is therefore due to other possible parts. 

Regards

**Comment by DavidMStraub** [comment]
Thanks, very good. Indeed the case of small numbers has to be dealt with somehow in the comparison; in most cases it is probably just noise. I will think about it.

But what is seen very nicely is that there are many cases where the ratio is close to 0.5 - this is the factor of 2 that is very likely due to the missing symmetrization discussed in issue #9. I am working on fixing this and will run your test again after I fixed it.

**Comment by DavidMStraub** [comment]
OK, so this is finally fixed after implementing the symmetrization, the omission of redundant entries, and weeding out a couple of bugs.

The numerical tests for Avelino's example file agree up to 10^-3 in absolute and 10^-5 in relative terms in the worst cases. There are some weird cases where the Mathematica code returns an imaginary part as large as 10^-9 while the Python version gives exact numerical zero for the beta function of this element; but these are very likely problems related to the numerical RG solvers (so, not our fault...). But might be useful to look into in more detail in the future.

**Comment by celis** [comment]
Yes it would be good to compare a bit the numerical RG solvers also.  Thanks for all the checks so far.
